# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - bash: |
      echo "This checks for formatting and common bash errors. See wiki for error details and ignore options: https://github.com/koalaman/shellcheck/wiki/SC1000"
      export scversion="stable"
      wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
      mv "shellcheck-${scversion}/shellcheck" .
      rm -r "shellcheck-${scversion}"
      ./shellcheck ./scripts/*.sh
    displayName: "Validate Scripts: Shellcheck"  

  - bash: |
      ls -l 
      echo "Now we can run our Makefile in $(pwd)"
      ./scripts/test/libs/bats/bin/bats ./scripts/test/setup_ubuntu_desktop.bats
    displayName: 'Run make all'
    workdir: $BUILD_SOURCESDIRECTORY
